
FROM node:16-alpine as builder
WORKDIR /usr/app
COPY ./package.json ./
RUN npm install
COPY ./ ./
RUN npm run build

#Run phase
#Base image
FROM node:16-alpine
WORKDIR /usr/app
COPY ./package.json ./

RUN npm install
COPY --from=builder /usr/app/dist .

CMD ["npm", "run", "serve"]
# CMD ["node", "server.js"]